//! Shared 15-state strapdown INS plant for the ESKF examples.
//!
//! The system under test — real strapdown mechanization (`v̇ = R(q)(a−bₐ)+g`,
//! Gauss–Markov biases), a matched synthetic IMU, and a position-fix
//! measurement — lives here so `eskf_nees` (single-trajectory smoke test) and
//! `mc_validation` (multi-trajectory consistency suite) drive *identical*
//! dynamics. AutoDiff derives the 15×15 F and the 3×15 H from these `DiffFn`s.
//!
//! Included by the examples with `#[path = "support/ins.rs"] mod ins;`. Cargo
//! does not build files under `examples/` subdirectories as their own examples,
//! so this is shared code, not a binary.

// Each example includes this module and uses only the subset it needs.
#![allow(dead_code)]

use filter::FilterState;
use manifold::diff::{AutoDiff, DiffFn};
use manifold::manifold::{Manifold, Rn, SO3, TimeVaryingConstraint, TrajectoryDynamics};
use nalgebra::{Quaternion, RealField, SMatrix, SVector, UnitQuaternion, Vector3};
use rand::SeedableRng;
use rand::rngs::StdRng;
use rand_distr::{Distribution, StandardNormal};

// ----- Allan-characterized IMU (tactical grade), shared by truth and filter --
pub const G: f64 = 9.80665;
pub const N_A: f64 = 0.02; // accel VRW spectral coeff, m/s²/√Hz
pub const N_G: f64 = 5e-4; // gyro ARW spectral coeff, rad/s/√Hz
pub const SIGMA_BA: f64 = 0.01; // accel bias-instability stationary σ, m/s²
pub const SIGMA_BG: f64 = 1e-4; // gyro bias-instability stationary σ, rad/s
pub const TAU: f64 = 100.0; // bias correlation time, s

// ----- Initial uncertainty (P₀ 1σ) = also the spread of the initial error ----
pub const SIGMA_P: f64 = 1.0; // m
pub const SIGMA_V: f64 = 0.1; // m/s
pub const SIGMA_TH: f64 = 0.02; // rad

// ----- GPS position-fix noise -----
pub const SIGMA_GPS: f64 = 0.5; // m, per axis

// ----- the 15-state product, generated by the macro (dims summed for us) -----
manifold::product_manifold! {
    pub struct Ins {
        p:  Rn<f64, 3> [3, 3],
        v:  Rn<f64, 3> [3, 3],
        q:  SO3<f64>   [4, 3],
        ba: Rn<f64, 3> [3, 3],
        bg: Rn<f64, 3> [3, 3],
    }
}

pub type Dynamics = TrajectoryDynamics<f64, AutoDiff<InsMechanization>, 16, 15, 6, 12, 34>;
pub type PositionConstraint = TimeVaryingConstraint<f64, AutoDiff<PositionFix>, 16, 15, 3>;

/// The strapdown velocity field, ready for `predict`.
pub fn dynamics() -> Dynamics {
    TrajectoryDynamics::new(AutoDiff::new(InsMechanization))
}
/// The position-fix measurement, ready for `correct_measurement`.
pub fn position_fix() -> PositionConstraint {
    TimeVaryingConstraint::new(AutoDiff::new(PositionFix))
}

pub fn state(
    p: Vector3<f64>,
    v: Vector3<f64>,
    q: SO3<f64>,
    ba: Vector3<f64>,
    bg: Vector3<f64>,
) -> Ins {
    Ins { p: Rn { x: p }, v: Rn { x: v }, q, ba: Rn { x: ba }, bg: Rn { x: bg } }
}
pub fn pos(s: &Ins) -> Vector3<f64> { s.p.x }
pub fn vel(s: &Ins) -> Vector3<f64> { s.v.x }
pub fn att(s: &Ins) -> &SO3<f64> { &s.q }
pub fn bias_a(s: &Ins) -> Vector3<f64> { s.ba.x }
pub fn bias_g(s: &Ins) -> Vector3<f64> { s.bg.x }
pub fn g_vec() -> Vector3<f64> { Vector3::new(0.0, 0.0, -G) }

// Block-diagonal P₀ from per-block 1σ; bias blocks carry the stationary GM var.
pub fn initial_covariance() -> SMatrix<f64, 15, 15> {
    let mut p0 = SMatrix::<f64, 15, 15>::zeros();
    let vars = [SIGMA_P, SIGMA_V, SIGMA_TH, SIGMA_BA, SIGMA_BG].map(|s| s * s);
    for (b, &var) in vars.iter().enumerate() {
        for i in 0..3 {
            p0[(3 * b + i, 3 * b + i)] = var;
        }
    }
    p0
}

// Discrete process-noise covariance for the W=12 noise channels. The framework
// forms G_d = G_cont·dt and adds G_d·N·G_dᵀ, so N is the continuous spectral
// density folded by an extra dt (white: N²/dt; bias RW: q/dt²).
pub fn process_noise(dt: f64) -> SMatrix<f64, 12, 12> {
    let mut n = SMatrix::<f64, 12, 12>::zeros();
    let q_a = N_A * N_A / dt;
    let q_g = N_G * N_G / dt;
    let q_ba = SIGMA_BA * SIGMA_BA * (1.0 - (-2.0 * dt / TAU).exp()) / (dt * dt);
    let q_bg = SIGMA_BG * SIGMA_BG * (1.0 - (-2.0 * dt / TAU).exp()) / (dt * dt);
    for i in 0..3 {
        n[(i, i)] = q_a;
        n[(i + 3, i + 3)] = q_g;
        n[(i + 6, i + 6)] = q_ba;
        n[(i + 9, i + 9)] = q_bg;
    }
    n
}

#[inline]
fn c<S: RealField>(x: f64) -> S {
    nalgebra::convert(x)
}

// Strapdown mechanization as a velocity field over packed [ambient|u|w] (34):
//   ambient: p 0..3, v 3..6, quat[w,i,j,k] 6..10, b_a 10..13, b_g 13..16
//   control: imu_a 16..19, imu_w 19..22
//   noise:   w_a 22..25, w_g 25..28, w_ba 28..31, w_bg 31..34
pub struct InsMechanization;
impl DiffFn<34, 15> for InsMechanization {
    fn eval<S: RealField + Copy>(&self, x: &SVector<S, 34>, y: &mut SVector<S, 15>) {
        let q = UnitQuaternion::from_quaternion(Quaternion::new(x[6], x[7], x[8], x[9]));
        // a_hat = imu_a + w_a − b_a (scale = identity); rotate into the nav frame.
        let a_hat = Vector3::new(
            x[16] + x[22] - x[10],
            x[17] + x[23] - x[11],
            x[18] + x[24] - x[12],
        );
        let a_nav = q.transform_vector(&a_hat);
        let g = c::<S>(G);
        let inv_tau = c::<S>(1.0 / TAU);

        // ṗ = v
        y[0] = x[3];
        y[1] = x[4];
        y[2] = x[5];
        // v̇ = R·a_hat + g_nav,  g_nav = [0, 0, −G]
        y[3] = a_nav[0];
        y[4] = a_nav[1];
        y[5] = a_nav[2] - g;
        // θ̇ = imu_w + w_g − b_g
        y[6] = x[19] + x[25] - x[13];
        y[7] = x[20] + x[26] - x[14];
        y[8] = x[21] + x[27] - x[15];
        // ḃ_a = −b_a/τ + w_ba
        y[9] = -x[10] * inv_tau + x[28];
        y[10] = -x[11] * inv_tau + x[29];
        y[11] = -x[12] * inv_tau + x[30];
        // ḃ_g = −b_g/τ + w_bg
        y[12] = -x[13] * inv_tau + x[31];
        y[13] = -x[14] * inv_tau + x[32];
        y[14] = -x[15] * inv_tau + x[33];
    }
}

// Position measurement h(x) = p.
pub struct PositionFix;
impl DiffFn<16, 3> for PositionFix {
    fn eval<S: RealField + Copy>(&self, x: &SVector<S, 16>, y: &mut SVector<S, 3>) {
        y[0] = x[0];
        y[1] = x[1];
        y[2] = x[2];
    }
}

// Synthetic IMU: Gauss–Markov bias (starts at 0) + matched white noise.
pub struct SyntheticImu {
    bias_a: Vector3<f64>,
    bias_g: Vector3<f64>,
    dt: f64,
    rng: StdRng,
}
impl SyntheticImu {
    pub fn new(dt: f64, seed: u64) -> Self {
        Self { bias_a: Vector3::zeros(), bias_g: Vector3::zeros(), dt, rng: StdRng::seed_from_u64(seed) }
    }
    pub fn sample(&mut self, f_b: Vector3<f64>, omega: Vector3<f64>) -> (Vector3<f64>, Vector3<f64>) {
        let decay = (-self.dt / TAU).exp();
        let drive = (1.0 - decay * decay).sqrt();
        self.bias_a = self.bias_a * decay + (SIGMA_BA * drive) * randn3(&mut self.rng);
        self.bias_g = self.bias_g * decay + (SIGMA_BG * drive) * randn3(&mut self.rng);
        let wn_a = (N_A / self.dt.sqrt()) * randn3(&mut self.rng);
        let wn_g = (N_G / self.dt.sqrt()) * randn3(&mut self.rng);
        (f_b + self.bias_a + wn_a, omega + self.bias_g + wn_g)
    }
    /// The IMU's realized accel bias (truth, for scoring the filter's estimate).
    pub fn bias_a(&self) -> Vector3<f64> { self.bias_a }
    /// The IMU's realized gyro bias.
    pub fn bias_g(&self) -> Vector3<f64> { self.bias_g }
}

pub fn randn3(rng: &mut StdRng) -> Vector3<f64> {
    Vector3::new(
        StandardNormal.sample(rng),
        StandardNormal.sample(rng),
        StandardNormal.sample(rng),
    )
}

pub fn control(a: Vector3<f64>, w: Vector3<f64>) -> SVector<f64, 6> {
    let mut u = SVector::<f64, 6>::zeros();
    u.fixed_rows_mut::<3>(0).copy_from(&a);
    u.fixed_rows_mut::<3>(3).copy_from(&w);
    u
}

// First-order manifold integration (same as the filter's predict mean), so a
// zero-noise filter reproduces truth exactly.
pub fn integrate(s: &Ins, dyn_engine: &Dynamics, u: &SVector<f64, 6>, dt: f64) -> Ins {
    let vel = dyn_engine.evaluate_velocity(&s.to_ambient(), u, &SVector::<f64, 12>::zeros());
    s.retract(&Ins::vector_to_tangent(&(vel * dt)))
}

/// A filter started off-truth by a draw from P₀ (error in-distribution at t=0).
pub fn perturbed_filter(truth: &Ins, rng: &mut StdRng) -> FilterState<f64, Ins, 16, 15> {
    let dp0 = SIGMA_P * randn3(rng);
    let dv0 = SIGMA_V * randn3(rng);
    let dth0 = SIGMA_TH * randn3(rng);
    let dba0 = SIGMA_BA * randn3(rng);
    let dbg0 = SIGMA_BG * randn3(rng);
    FilterState::new(
        state(
            pos(truth) - dp0,
            vel(truth) - dv0,
            att(truth).retract(&(-dth0)),
            bias_a(truth) - dba0,
            bias_g(truth) - dbg0,
        ),
        initial_covariance(),
    )
}

/// The 15-state estimation error in the filter's tangent coordinates, scored
/// against P for NEES: [δp, δv, δθ (local_lift), δbₐ, δb_g].
pub fn nees_error(truth: &Ins, est: &Ins, imu: &SyntheticImu) -> SVector<f64, 15> {
    let mut e = SVector::<f64, 15>::zeros();
    e.fixed_rows_mut::<3>(0).copy_from(&(pos(truth) - pos(est)));
    e.fixed_rows_mut::<3>(3).copy_from(&(vel(truth) - vel(est)));
    e.fixed_rows_mut::<3>(6).copy_from(&att(est).local_lift(att(truth)));
    e.fixed_rows_mut::<3>(9).copy_from(&(imu.bias_a() - bias_a(est)));
    e.fixed_rows_mut::<3>(12).copy_from(&(imu.bias_g() - bias_g(est)));
    e
}

// ---------------------------------------------------------------------------
// Trajectory battery + a high-fidelity reference integrator (for validation).
// ---------------------------------------------------------------------------

/// A trajectory profile: an initial nav velocity and the continuous inputs
/// (desired nav acceleration, body angular rate) as a function of time and
/// current nav velocity. Shared by `mc_validation` and `integration_fidelity`.
pub struct Profile {
    pub name: &'static str,
    pub v0: Vector3<f64>,
    pub inputs: fn(f64, Vector3<f64>) -> (Vector3<f64>, Vector3<f64>),
}

/// Battery spanning benign-to-aggressive dynamics.
pub fn profiles() -> [Profile; 4] {
    [
        Profile {
            name: "static hover",
            v0: Vector3::zeros(),
            inputs: |_t, _v| (Vector3::zeros(), Vector3::zeros()),
        },
        Profile {
            name: "constant velocity",
            v0: Vector3::new(12.0, 0.0, 0.0),
            inputs: |_t, _v| (Vector3::zeros(), Vector3::zeros()),
        },
        Profile {
            name: "coordinated turn",
            v0: Vector3::new(10.0, 0.0, 0.0),
            inputs: |_t, v| {
                let w = Vector3::new(0.0, 0.0, 0.3); // 0.3 rad/s yaw, radius ~33 m
                (w.cross(&v), w) // centripetal accel keeps |v| constant
            },
        },
        Profile {
            name: "aggressive 3-D",
            v0: Vector3::new(15.0, 0.0, 0.0),
            inputs: |t, v| {
                // Coupled roll/pitch oscillation + steady fast yaw, plus a
                // vertical accel — large attitude increments per step.
                let w = Vector3::new(0.3 * (0.5 * t).sin(), 0.2 * (0.7 * t).cos(), 0.5);
                let a = w.cross(&v) + Vector3::new(0.0, 0.0, 2.0 * (0.8 * t).sin());
                (a, w)
            },
        },
    ]
}

/// High-fidelity reference advance of the *continuous* kinematics defined by
/// `inputs` over `dt`: classic RK4 on (ṗ = v, v̇ = a_nav(t, v)) plus the exact
/// exponential map on attitude (q ← q·Exp(ω·h)), over `M` fine substeps. The
/// kinematic reference leaves the biases untouched (those are the IMU's). This
/// is the "truth" that first-order Euler is measured against — generating truth
/// with a *different, higher-order* integrator is what lets `integration_fidelity`
/// see the integration error that `mc_validation` structurally cannot.
pub fn reference_step(
    s: &Ins,
    t: f64,
    dt: f64,
    inputs: fn(f64, Vector3<f64>) -> (Vector3<f64>, Vector3<f64>),
) -> Ins {
    reference_step_with_imu(s, t, dt, inputs).0
}

/// Like [`reference_step`], but also returns the *interval-averaged* specific
/// force and angular rate over `[t, t+dt]` — the delta-velocity / delta-angle a
/// real strapdown IMU integrates and reports, in contrast to a single
/// start-of-interval (zero-order-hold) sample. Feeding these to the rate-form
/// mechanization captures the within-step motion the ZOH sample misses.
pub fn reference_step_with_imu(
    s: &Ins,
    t: f64,
    dt: f64,
    inputs: fn(f64, Vector3<f64>) -> (Vector3<f64>, Vector3<f64>),
) -> (Ins, Vector3<f64>, Vector3<f64>) {
    const M: usize = 100;
    let h = dt / M as f64;
    let g = g_vec();
    let a_of = |tt: f64, vv: Vector3<f64>| inputs(tt, vv).0;
    let mut p = pos(s);
    let mut v = vel(s);
    let mut q = att(s).uq;
    let mut f_int = Vector3::zeros(); // ∫ specific force (body frame)
    let mut w_int = Vector3::zeros(); // ∫ angular rate
    for j in 0..M {
        let tj = t + j as f64 * h;
        let (a_nav, omega) = inputs(tj, v);
        // Accumulate the body-frame specific force and rate over the substep.
        f_int += q.inverse_transform_vector(&(a_nav - g)) * h;
        w_int += omega * h;
        // Attitude: exact exponential map with the substep-midpoint rate.
        let w_mid = inputs(tj + 0.5 * h, v).1;
        q = q * UnitQuaternion::from_scaled_axis(w_mid * h);
        // Translation: classic RK4 of ṗ = v, v̇ = a_nav(t, v).
        let k1v = a_of(tj, v);
        let k1p = v;
        let k2v = a_of(tj + 0.5 * h, v + k1v * (0.5 * h));
        let k2p = v + k1v * (0.5 * h);
        let k3v = a_of(tj + 0.5 * h, v + k2v * (0.5 * h));
        let k3p = v + k2v * (0.5 * h);
        let k4v = a_of(tj + h, v + k3v * h);
        let k4p = v + k3v * h;
        v += (k1v + k2v * 2.0 + k3v * 2.0 + k4v) * (h / 6.0);
        p += (k1p + k2p * 2.0 + k3p * 2.0 + k4p) * (h / 6.0);
    }
    (state(p, v, SO3 { uq: q }, bias_a(s), bias_g(s)), f_int / dt, w_int / dt)
}
