//! Monte-Carlo consistency validation for the manifold-framework INS ESKF.
//!
//! Where `eskf_nees` checks one trajectory, this drives the *same* 15-state
//! plant (`support/ins.rs`) over a battery of trajectory profiles — from a
//! static hover to an aggressive 3-D maneuver — and subjects each to the two
//! standard consistency tests over an ensemble of independent runs:
//!
//!   * NEES — normalized estimation-error squared (needs truth):  E[η] = 15.
//!   * NIS  — normalized innovation squared (online-observable):   E[η] = 3.
//!
//! For an M-run ensemble the per-epoch average is χ²-distributed; a profile is
//! accepted when its post-burn-in grand mean lands inside the two-sided 95%
//! interval AND most epochs stay within the per-epoch band. A profile that
//! drifts out signals an inconsistent filter — an over- or under-confident
//! covariance (the linearization, transport, or noise bookkeeping is off).
//!
//! NOTE: truth is generated by the *same* discrete mechanization the filter
//! assumes, so this validates the *estimator* (transport, Jacobians, noise
//! bookkeeping) — not the fidelity of first-order integration to real physics.
//! The aggressive profile still stresses the linearization hard (large attitude
//! increments per step), which is where an EKF most often becomes inconsistent.
//!
//! Run:  cargo run --release -p filter --example mc_validation

#[path = "support/ins.rs"]
mod ins;
use ins::*;

use filter::Integrator;
use manifold::manifold::SO3;
use nalgebra::{Matrix3, SMatrix, Vector3};
use rand::SeedableRng;
use rand::rngs::StdRng;

const DT: f64 = 0.02; // 50 Hz
const N_STEPS: usize = 3000; // 60 s
const FIX_EVERY: usize = 25; // 0.5 s GPS
const RUNS: usize = 50;
const BURN_IN_S: f64 = 5.0;
const Z95: f64 = 1.959964; // two-sided 95% normal quantile

// Wilson–Hilferty normal approximation to the χ²_k quantile — exact to well
// under a percent for the k = dof·RUNS ≳ 150 used here. No stats dependency.
fn chi2_quantile(k: f64, z: f64) -> f64 {
    let h = 2.0 / (9.0 * k);
    k * (1.0 - h + z * h.sqrt()).powi(3)
}

// 95% acceptance band for the M-run ensemble average of an n-dof statistic.
fn band(dof: f64) -> (f64, f64) {
    let k = dof * RUNS as f64;
    (chi2_quantile(k, -Z95) / RUNS as f64, chi2_quantile(k, Z95) / RUNS as f64)
}

// Post-burn-in per-epoch ensemble means of NEES and NIS for one profile.
fn run_profile(
    p: &Profile,
    dyn_engine: &Dynamics,
    meas: &PositionConstraint,
    q_noise: &SMatrix<f64, 12, 12>,
    r_gps: &Matrix3<f64>,
) -> (Vec<f64>, Vec<f64>) {
    let n_samples = N_STEPS / FIX_EVERY;
    let mut nees_sum = vec![0.0f64; n_samples];
    let mut nis_sum = vec![0.0f64; n_samples];
    let g = g_vec();

    for run in 0..RUNS {
        let mut rng = StdRng::seed_from_u64(run as u64);
        let mut imu = SyntheticImu::new(DT, 10_000 + run as u64);
        let mut truth = state(Vector3::zeros(), p.v0, SO3::identity(), Vector3::zeros(), Vector3::zeros());
        let mut filter = perturbed_filter(&truth, &mut rng);

        let mut si = 0;
        for k in 1..=N_STEPS {
            let t = k as f64 * DT;
            let (a_nav, omega) = (p.inputs)(t, vel(&truth));
            let r = att(&truth).uq;
            let f_b = r.inverse_transform_vector(&(a_nav - g));

            let (accel, gyro) = imu.sample(f_b, omega);
            filter.predict(dyn_engine, &control(accel, gyro), q_noise, DT, Integrator::Euler);
            truth = integrate(&truth, dyn_engine, &control(f_b, omega), DT);

            if k % FIX_EVERY == 0 {
                let gps = pos(&truth) + SIGMA_GPS * randn3(&mut rng);

                // NIS (pre-update). For h(x)=p the tangent H = [I₃ | 0], so the
                // innovation covariance is S = P_pp + R.
                let innov = gps - pos(&filter.state);
                let s = filter.covariance.fixed_view::<3, 3>(0, 0) + r_gps;
                nis_sum[si] += innov.dot(&(s.try_inverse().expect("S singular") * innov));

                filter.correct_measurement(meas, &gps, r_gps);

                // NEES (post-update).
                let e = nees_error(&truth, &filter.state, &imu);
                let pinv = filter.covariance.try_inverse().expect("P singular");
                nees_sum[si] += e.dot(&(pinv * e));
                si += 1;
            }
        }
    }

    let mut nees = Vec::new();
    let mut nis = Vec::new();
    for i in 0..n_samples {
        if (((i + 1) * FIX_EVERY) as f64 * DT) >= BURN_IN_S {
            nees.push(nees_sum[i] / RUNS as f64);
            nis.push(nis_sum[i] / RUNS as f64);
        }
    }
    (nees, nis)
}

fn mean(v: &[f64]) -> f64 {
    v.iter().sum::<f64>() / v.len() as f64
}
fn frac_in(v: &[f64], lo: f64, hi: f64) -> f64 {
    v.iter().filter(|&&x| x >= lo && x <= hi).count() as f64 / v.len() as f64
}

fn main() {
    let dyn_engine = dynamics();
    let meas = position_fix();
    let q_noise = process_noise(DT);
    let r_gps = Matrix3::identity() * SIGMA_GPS * SIGMA_GPS;

    let (lo15, hi15) = band(15.0); // NEES
    let (lo3, hi3) = band(3.0); // NIS

    println!("=== Monte-Carlo consistency validation — 15-state INS ESKF ===");
    println!(
        "  {RUNS} runs × {:.0}s @ {:.0}Hz, GPS every {:.1}s, burn-in {:.0}s",
        N_STEPS as f64 * DT,
        1.0 / DT,
        FIX_EVERY as f64 * DT,
        BURN_IN_S
    );
    println!("  NEES 95% band (15 dof): [{lo15:.2}, {hi15:.2}]   E[η] = 15");
    println!("  NIS  95% band ( 3 dof): [{lo3:.2}, {hi3:.2}]   E[η] = 3");
    println!();
    println!(
        "  {:<20} {:>8} {:>8} | {:>7} {:>8} | {}",
        "profile", "NEES", "in-band", "NIS", "in-band", "verdict"
    );

    let mut all_pass = true;
    for p in &profiles() {
        let (nees, nis) = run_profile(p, &dyn_engine, &meas, &q_noise, &r_gps);
        let (nees_mean, nis_mean) = (mean(&nees), mean(&nis));
        let (nees_in, nis_in) = (frac_in(&nees, lo15, hi15), frac_in(&nis, lo3, hi3));

        // Grand mean inside the band (strong), and most epochs in band (per-epoch).
        let pass = nees_mean >= lo15
            && nees_mean <= hi15
            && nis_mean >= lo3
            && nis_mean <= hi3
            && nees_in >= 0.80
            && nis_in >= 0.80;
        all_pass &= pass;

        println!(
            "  {:<20} {:>8.2} {:>7.0}% | {:>7.2} {:>7.0}% | {}",
            p.name,
            nees_mean,
            100.0 * nees_in,
            nis_mean,
            100.0 * nis_in,
            if pass { "PASS" } else { "FAIL" }
        );
    }

    println!();
    assert!(all_pass, "ESKF failed Monte-Carlo consistency on at least one profile");
    println!("OK: filter is statistically consistent across all trajectory profiles.");
}
